language: python

matrix:
  include:
    - python: '3.7'
      name: "flake8"
      env: TOXENV="flake8"
      dist: xenial

    - python: '2.7'
      env:
        - RUN_BENCHMARKS: true
        - SO_S3_URL: "s3://smart-open-py27-benchmark"
        - SO_S3_RESULT_URL: "s3://smart-open-py27-benchmark-results"
        - BOTO_CONFIG: "/dev/null"
        - TOXENV: "check_keys"

    - python: '3.5'
      env: TOXENV="check_keys"


    - python: '3.6'
      env:
        - RUN_BENCHMARKS: true
        - SO_S3_URL: "s3://smart-open-py36-benchmark"
        - SO_S3_RESULT_URL: "s3://smart-open-py36-benchmark-results"
        - BOTO_CONFIG: "/dev/null"
        - TOXENV: "check_keys"


    - python: '3.7'
      dist: xenial
      env:
        - RUN_BENCHMARKS: true
        - SO_S3_URL: "s3://smart-open-py37-benchmark"
        - SO_S3_RESULT_URL: "s3://smart-open-py37-benchmark-results"
        - SO_ENABLE_MOTO_SERVER: "1"
        - BOTO_CONFIG: "/dev/null"
        - TOXENV: "check_keys"

      dist: xenial

install:
  - pip install tox

script: tox -vv

cache:
  directories:
  - "$HOME/.cache/pip"
  - "$HOME/.pyenv"
