language: python

env:
  global:
    - secure: "GH+DI7f9QenVtTZFEfn4B8wO5JJK65PkHDg8vY/npdW51y5PPAynTEf/++D0H4tjwqMuXwB5lrbWfYeskf29Xuq5MT5+FixajZFcbhscoSM9CGABeph2s2+Hm4kSIKmjnTlQLgJHVbwypnlU/W4sfMCbqeOmv2fYXCCt0GhtnWc="
    - secure: "du3PQYEiDPw55TRzhk+Ocv1Gx1DuusbCSMVSQmccAoyOr7qxDqm+1jh2v13RmajNK7FnlKyC4xSTySVpSl70By2uhZlJT43EpenqIcpQWqUAm3nVr6etszdb1A6TfEGQrxZ8Y2j9KD6QAMNovsMZbl0bcDJDxTeFA4P/yU9UZcI="


matrix:
  include:
    - python: '2.7'
      name: 'python2.7 test'
      env:
        - SO_DISABLE_MOCKS: "1"
        - SO_DISABLE_MOTO_SERVER: "1"
        - SO_S3_URL: "s3://smart-open-py27-benchmark"
        - SO_S3_RESULT_URL: "s3://smart-open-py27-benchmark-results"
        - TOXENV: py27-test,py27-integration,py27-benchmark

    - python: '3.5'
      name: 'flake8'
      env:
        - TOXENV: flake8

    - python: '3.5'
      name: 'python3.5 test (mocked)'
      env:
        - TOXENV: py35-test,py35-integration,py35-benchmark

    - python: '3.6'
      name: 'python3.6 test'
      env:
        - SO_DISABLE_MOCKS: "1"
        - SO_DISABLE_MOTO_SERVER: "1"
        - SO_S3_URL: "s3://smart-open-py36-benchmark"
        - SO_S3_RESULT_URL: "s3://smart-open-py36-benchmark-results"
        - TOXENV: py36-test,py36-integration,py36-benchmark

    - python: '3.7'
      name: 'python3.7 test'
      env:
        - SO_DISABLE_MOCKS: "1"
        - SO_DISABLE_MOTO_SERVER: "1"
        - SO_S3_URL: "s3://smart-open-py37-benchmark"
        - SO_S3_RESULT_URL: "s3://smart-open-py37-benchmark-results"
        - BOTO_CONFIG: "/dev/null"
        - TOXENV: py37-test,py37-integration,py37-benchmark
      dist: xenial

install:
  - pip install tox==3.7.0

script:
  - if [[ ${TRAVIS_SECURE_ENV_VARS} = false ]]; then
      echo "DISABLE INTEGRATION TESTING FOR S3";
      unset SO_DISABLE_MOCKS;
      unset SO_S3_URL;
      unset SO_S3_RESULT_URL;
    fi
  - tox -vv

cache:
  directories:
  - "$HOME/.cache/pip"
  - "$HOME/.pyenv"
  - "$HOME/.ccache"
  - "$HOME/.pip-cache"
