language: python

matrix:
  include:
    - python: '2.7'
      env:
        - SO_DISABLE_MOCKS: "1"
        - SO_S3_URL: "s3://smart-open-py27-benchmark"
        - SO_S3_RESULT_URL: "s3://smart-open-py27-benchmark-results"
        - BOTO_CONFIG: "/dev/null"

    - python: '3.5'

    - python: '3.6'
      env:
        - SO_DISABLE_MOCKS: "1"
        - SO_S3_URL: "s3://smart-open-py36-benchmark"
        - SO_S3_RESULT_URL: "s3://smart-open-py36-benchmark-results"
        - BOTO_CONFIG: "/dev/null"

    - python: '3.7'
      dist: xenial
      env:
        - SO_DISABLE_MOCKS: "1"
        - SO_S3_URL: "s3://smart-open-py37-benchmark"
        - SO_S3_RESULT_URL: "s3://smart-open-py37-benchmark-results"
        - BOTO_CONFIG: "/dev/null"
      dist: xenial

    - python: '3.7'
      dist: xenial

    - python: '3.7'
      dist: xenial
      env:
        - SO_ENABLE_MOTO_SERVER: "1"


install:
  - pip install --upgrade setuptools
  - pip install flask
  - pip install .[test]
  - pip install flake8
  - pip install pytest
  - pip freeze


script:
  - if [[ ${TRAVIS_SECURE_ENV_VARS} = false ]]; then
      echo "DISABLE INTEGRATION TESTING FOR S3";
      unset SO_DISABLE_MOCKS;
      unset SO_S3_URL;
      unset SO_S3_RESULT_URL;
    fi
  - if [[ ${SO_DISABLE_MOTO_SERVER} -ne 1 ]]; then
      sh -c "moto_server -p5000 2> /dev/null &";
    fi
  - flake8 --max-line-length=110
  - python check_keys.py
  - pytest smart_open/tests/test_s3.py
  - python setup.py test  # I suspect something is trashing the keys in the environment
  - python check_keys.py
  - export SO_S3_URL=$SO_S3_URL/$(python -c 'from uuid import uuid4;print(uuid4())')
  - py.test integration-tests/test_http.py
  - if [[ ${SO_DISABLE_MOCKS} = "1" ]]; then
      pip install pytest_benchmark awscli;
      set -e;
      py.test integration-tests/test_s3.py --benchmark-save=`git rev-parse HEAD`;
      set +e;
      aws s3 cp .benchmarks/*/*.json ${SO_S3_RESULT_URL};
      aws s3 rm --recursive $SO_S3_URL;
    fi
  - pip install numpy
  - py.test integration-tests/test_207.py


cache:
  directories:
  - "$HOME/.cache/pip"
  - "$HOME/.pyenv"
