name: Test smart_open using tox under Windows
on: push
jobs:
  build:
    runs-on: windows-2019
    strategy:
      matrix:
        include:
          - python-version: '3.6'
            toxenv: "py36-doctest,py36-test"
            result_key: benchmark-results-py36

          - python-version: '3.7'
            toxenv: "py37-doctest,py37-test"
            enable_moto_server: "1"

          - python-version: '3.8'
            toxenv: "py38-doctest,py38-test"

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install tox
        run: pip install tox

      - name: Test using Tox
        run: tox -vv
